// GENERATED by experiment/export_app_data.py — do not edit by hand.
// Sources: experiment/samples/reference.json, experiment/raw/after.jsonl (trial 1),
//          experiment/results/msa-metrics.json. All data is simulated / semi-synthetic.
import type { RawReferenceSample, RawMsaSummary } from './types';

export const GEOMETRY = {"diePx": 1000, "umPerPx": 5.0, "sealRingPx": [20, 24], "padSizePx": 16, "padOffsetPx": 40} as const;

export const REFERENCE_SAMPLES: RawReferenceSample[] = [
 {
  "id": "S01",
  "group": "defective",
  "note": "SCR core 150µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 150.0,
    "crossesPad": false,
    "location": {
     "x": 502,
     "y": 587
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 150,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 150,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 500,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S02",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S03",
  "group": "defective",
  "note": "boundary SCR peripheral 250µm (Pass)",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 250.0,
    "crossesPad": false,
    "location": {
     "x": 11,
     "y": 407
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S04",
  "group": "defective",
  "note": "CON core 3pt 25/30/35µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 25,
    "location": {
     "x": 244,
     "y": 300
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30,
    "location": {
     "x": 369,
     "y": 580
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 35,
    "location": {
     "x": 670,
     "y": 798
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S05",
  "group": "defective",
  "note": "CON peripheral 60µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CON",
    "zone": "peripheral",
    "diameterUm": 60,
    "location": {
     "x": 9,
     "y": 241
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 60
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S06",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S07",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S08",
  "group": "defective",
  "note": "boundary CHP 25µm (Warning)",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 25,
    "touchesSealRing": false,
    "location": {
     "x": 721,
     "y": 5
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S09",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S10",
  "group": "good",
  "note": "sub-threshold CON core 15µm + CHP 6µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15,
    "location": {
     "x": 136,
     "y": 358
    }
   },
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 6,
    "touchesSealRing": false,
    "location": {
     "x": 998,
     "y": 498
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S11",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S12",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S13",
  "group": "defective",
  "note": "SCR peripheral 400µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 400.3,
    "crossesPad": false,
    "location": {
     "x": 10,
     "y": 677
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S14",
  "group": "good",
  "note": "sub-threshold SCR core 70µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 70.0,
    "crossesPad": false,
    "location": {
     "x": 738,
     "y": 148
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 75
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 60
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 55
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 50
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 65
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 70
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 150,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S15",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S16",
  "group": "defective",
  "note": "CRK peripheral 150µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CRK",
    "zone": "peripheral",
    "lengthUm": 158.7,
    "location": {
     "x": 5,
     "y": 560
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 5,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S17",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S18",
  "group": "defective",
  "note": "CHP into core 150µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CHP",
    "zone": "core",
    "depthUm": 150,
    "touchesSealRing": true,
    "location": {
     "x": 969,
     "y": 724
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 50
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 50
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 30
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S19",
  "group": "defective",
  "note": "CON core 2pt 25/40µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 25,
    "location": {
     "x": 577,
     "y": 463
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 40,
    "location": {
     "x": 327,
     "y": 581
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S20",
  "group": "defective",
  "note": "CON core 70µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 70,
    "location": {
     "x": 268,
     "y": 415
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S21",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S22",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S23",
  "group": "defective",
  "note": "CHP touches seal ring 105µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 105,
    "touchesSealRing": true,
    "location": {
     "x": 978,
     "y": 800
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 20,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 25,
      "touchesSealRing": true
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S24",
  "group": "defective",
  "note": "boundary CHP 8µm (Pass)",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 8,
    "touchesSealRing": false,
    "location": {
     "x": 783,
     "y": 997
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S25",
  "group": "defective",
  "note": "SCR core 450µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 450.0,
    "crossesPad": false,
    "location": {
     "x": 320,
     "y": 336
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 650,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 250,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 650,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S26",
  "group": "good",
  "note": "sub-threshold SCR peripheral 150µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 150.4,
    "crossesPad": false,
    "location": {
     "x": 7,
     "y": 589
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 10,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S27",
  "group": "good",
  "note": "sub-threshold CHP 5µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 5,
    "touchesSealRing": false,
    "location": {
     "x": 1,
     "y": 567
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S28",
  "group": "defective",
  "note": "CHP 12µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 12,
    "touchesSealRing": false,
    "location": {
     "x": 2,
     "y": 543
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 10,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S29",
  "group": "good",
  "note": "sub-threshold CON core 12µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 12,
    "location": {
     "x": 759,
     "y": 407
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S30",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S31",
  "group": "good",
  "note": "sub-threshold CON peripheral 35µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "peripheral",
    "diameterUm": 35,
    "location": {
     "x": 168,
     "y": 985
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S32",
  "group": "good",
  "note": "sub-threshold CON core 15µm×2",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15,
    "location": {
     "x": 658,
     "y": 869
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15,
    "location": {
     "x": 134,
     "y": 331
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S33",
  "group": "defective",
  "note": "CHP 20µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 20,
    "touchesSealRing": false,
    "location": {
     "x": 315,
     "y": 995
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S34",
  "group": "defective",
  "note": "CRK core 400µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CRK",
    "zone": "core",
    "lengthUm": 400.0,
    "location": {
     "x": 800,
     "y": 786
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 200,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 300,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 300,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S35",
  "group": "defective",
  "note": "CON core 1pt 30µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30,
    "location": {
     "x": 894,
     "y": 222
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S36",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S37",
  "group": "defective",
  "note": "boundary SCR core 280µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 280.0,
    "crossesPad": false,
    "location": {
     "x": 299,
     "y": 747
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 325,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 300,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 1350,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S38",
  "group": "defective",
  "note": "CHP 40µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 40,
    "touchesSealRing": false,
    "location": {
     "x": 369,
     "y": 991
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S39",
  "group": "defective",
  "note": "SCR core 180µm crosses pad",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 180.0,
    "crossesPad": true,
    "location": {
     "x": 491,
     "y": 53
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 100,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 60,
      "crossesPad": false
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 50,
      "crossesPad": false
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S40",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 50
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 35
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 40
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 55
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 30
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 45
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 }
];

export const MSA_SUMMARY: RawMsaSummary = {
 "before": {
  "repeatability": 0.8873239436619719,
  "repeatabilityN": 71,
  "betweenAppraisersPerTrial": 0.575,
  "allVsStandard": 0.425,
  "accuracy": 0.6,
  "missRate": 0.14814814814814814,
  "falseCallRate": 0.0,
  "warningRate": 0.425,
  "referenceWarningRate": 0.225,
  "fleissKappa": 0.43127962085308064,
  "judgments": 120
 },
 "after": {
  "repeatability": null,
  "repeatabilityN": 0,
  "betweenAppraisersPerTrial": 0.6,
  "allVsStandard": 0.475,
  "accuracy": 0.6083333333333333,
  "missRate": 0.37037037037037035,
  "falseCallRate": 0.030303030303030304,
  "warningRate": 0.23333333333333334,
  "referenceWarningRate": 0.225,
  "fleissKappa": 0.39039408866995073,
  "judgments": 120
 },
 "recognition": {
  "CHP": {
   "refInstances": 27,
   "tp": 4,
   "fn": 23,
   "recall": 0.14814814814814814,
   "measBiasUm": -64.25
  },
  "CRK": {
   "refInstances": 6,
   "tp": 0,
   "fn": 6,
   "recall": 0.0,
   "measBiasUm": null
  },
  "SCR": {
   "refInstances": 24,
   "tp": 13,
   "fn": 11,
   "recall": 0.5416666666666666,
   "measBiasUm": 110.38461538461539
  },
  "CON": {
   "refInstances": 39,
   "tp": 23,
   "fn": 16,
   "recall": 0.5897435897435898,
   "measBiasUm": -23.695652173913043
  }
 }
};
