// GENERATED by experiment/export_app_data.py — do not edit by hand.
// Sources: experiment/samples/reference.json, experiment/raw/after.jsonl (trial 1),
//          experiment/results/msa-metrics.json, experiment/results/self-judgment-filled.xlsx (+ meta).
// Samples are semi-synthetic and AI appraisers are simulated; the human rounds are the author's own judgments.
// Second round (spec v2): experiment/results/v2-metrics.json (written by analyze_v2.py).
import type { RawReferenceSample, RawMsaSummary, RawHumanSummary, RawHumanReply, RawV2Summary } from './types';

export const GEOMETRY = {"diePx": 1000, "umPerPx": 5.0, "sealRingPx": [20, 24], "padSizePx": 16, "padOffsetPx": 40} as const;

export const REFERENCE_SAMPLES: RawReferenceSample[] = [
 {
  "id": "S01",
  "group": "defective",
  "note": "SCR core 150µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 150.0,
    "crossesPad": false,
    "location": {
     "x": 502,
     "y": 587
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 150,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 150,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 500,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S02",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S03",
  "group": "defective",
  "note": "boundary SCR peripheral 250µm (Pass)",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 250.0,
    "crossesPad": false,
    "location": {
     "x": 11,
     "y": 407
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S04",
  "group": "defective",
  "note": "CON core 3pt 25/30/35µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 25,
    "location": {
     "x": 244,
     "y": 300
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30,
    "location": {
     "x": 369,
     "y": 580
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 35,
    "location": {
     "x": 670,
     "y": 798
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S05",
  "group": "defective",
  "note": "CON peripheral 60µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CON",
    "zone": "peripheral",
    "diameterUm": 60,
    "location": {
     "x": 9,
     "y": 241
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 60
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S06",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S07",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S08",
  "group": "defective",
  "note": "boundary CHP 25µm (Warning)",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 25,
    "touchesSealRing": false,
    "location": {
     "x": 721,
     "y": 5
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S09",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S10",
  "group": "good",
  "note": "sub-threshold CON core 15µm + CHP 6µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15,
    "location": {
     "x": 136,
     "y": 358
    }
   },
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 6,
    "touchesSealRing": false,
    "location": {
     "x": 998,
     "y": 498
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S11",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S12",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S13",
  "group": "defective",
  "note": "SCR peripheral 400µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 400.3,
    "crossesPad": false,
    "location": {
     "x": 10,
     "y": 677
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S14",
  "group": "good",
  "note": "sub-threshold SCR core 70µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 70.0,
    "crossesPad": false,
    "location": {
     "x": 738,
     "y": 148
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 75
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 60
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 55
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 50
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 65
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 70
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 150,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S15",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S16",
  "group": "defective",
  "note": "CRK peripheral 150µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CRK",
    "zone": "peripheral",
    "lengthUm": 158.7,
    "location": {
     "x": 5,
     "y": 560
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 5,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S17",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S18",
  "group": "defective",
  "note": "CHP into core 150µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CHP",
    "zone": "core",
    "depthUm": 150,
    "touchesSealRing": true,
    "location": {
     "x": 969,
     "y": 724
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 50
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 50
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 30
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S19",
  "group": "defective",
  "note": "CON core 2pt 25/40µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 25,
    "location": {
     "x": 577,
     "y": 463
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 40,
    "location": {
     "x": 327,
     "y": 581
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S20",
  "group": "defective",
  "note": "CON core 70µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 70,
    "location": {
     "x": 268,
     "y": 415
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S21",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S22",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S23",
  "group": "defective",
  "note": "CHP touches seal ring 105µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 105,
    "touchesSealRing": true,
    "location": {
     "x": 978,
     "y": 800
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 20,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 25,
      "touchesSealRing": true
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S24",
  "group": "defective",
  "note": "boundary CHP 8µm (Pass)",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 8,
    "touchesSealRing": false,
    "location": {
     "x": 783,
     "y": 997
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S25",
  "group": "defective",
  "note": "SCR core 450µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 450.0,
    "crossesPad": false,
    "location": {
     "x": 320,
     "y": 336
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 650,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 250,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 650,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S26",
  "group": "good",
  "note": "sub-threshold SCR peripheral 150µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 150.4,
    "crossesPad": false,
    "location": {
     "x": 7,
     "y": 589
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 15,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 10,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S27",
  "group": "good",
  "note": "sub-threshold CHP 5µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 5,
    "touchesSealRing": false,
    "location": {
     "x": 1,
     "y": 567
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S28",
  "group": "defective",
  "note": "CHP 12µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 12,
    "touchesSealRing": false,
    "location": {
     "x": 2,
     "y": 543
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CHP",
      "zone": "peripheral",
      "depthUm": 10,
      "touchesSealRing": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S29",
  "group": "good",
  "note": "sub-threshold CON core 12µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 12,
    "location": {
     "x": 759,
     "y": 407
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S30",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S31",
  "group": "good",
  "note": "sub-threshold CON peripheral 35µm",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "peripheral",
    "diameterUm": 35,
    "location": {
     "x": 168,
     "y": 985
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S32",
  "group": "good",
  "note": "sub-threshold CON core 15µm×2",
  "referenceVerdict": "pass",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15,
    "location": {
     "x": 658,
     "y": 869
    }
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15,
    "location": {
     "x": 134,
     "y": 331
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S33",
  "group": "defective",
  "note": "CHP 20µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 20,
    "touchesSealRing": false,
    "location": {
     "x": 315,
     "y": 995
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 25
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S34",
  "group": "defective",
  "note": "CRK core 400µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CRK",
    "zone": "core",
    "lengthUm": 400.0,
    "location": {
     "x": 800,
     "y": 786
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 200,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 300,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 300,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   }
  ]
 },
 {
  "id": "S35",
  "group": "defective",
  "note": "CON core 1pt 30µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30,
    "location": {
     "x": 894,
     "y": 222
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 10
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 15
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S36",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S37",
  "group": "defective",
  "note": "boundary SCR core 280µm",
  "referenceVerdict": "warning",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 280.0,
    "crossesPad": false,
    "location": {
     "x": 299,
     "y": 747
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 325,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 300,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 1350,
      "crossesPad": false
     }
    ],
    "pyVerdict": "fail"
   }
  ]
 },
 {
  "id": "S38",
  "group": "defective",
  "note": "CHP 40µm",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 40,
    "touchesSealRing": false,
    "location": {
     "x": 369,
     "y": 991
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "peripheral",
      "diameterUm": 20
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S39",
  "group": "defective",
  "note": "SCR core 180µm crosses pad",
  "referenceVerdict": "fail",
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 180.0,
    "crossesPad": true,
    "location": {
     "x": 491,
     "y": 53
    }
   }
  ],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 100,
      "crossesPad": false
     }
    ],
    "pyVerdict": "warning"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 60,
      "crossesPad": false
     }
    ],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "SCR",
      "zone": "core",
      "lengthUm": 50,
      "crossesPad": false
     }
    ],
    "pyVerdict": "pass"
   }
  ]
 },
 {
  "id": "S40",
  "group": "good",
  "note": "clean",
  "referenceVerdict": "pass",
  "defects": [],
  "recorded": [
   {
    "appraiser": "甲",
    "shift": "日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   },
   {
    "appraiser": "乙",
    "shift": "夜班",
    "model": "claude-sonnet-4-6",
    "defects": [
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 50
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 35
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 40
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 55
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 30
     },
     {
      "code": "CON",
      "zone": "core",
      "diameterUm": 45
     }
    ],
    "pyVerdict": "fail"
   },
   {
    "appraiser": "丙",
    "shift": "假日班",
    "model": "claude-sonnet-4-6",
    "defects": [],
    "pyVerdict": "pass"
   }
  ]
 }
];

export const MSA_SUMMARY: RawMsaSummary = {
 "before": {
  "repeatability": 0.8583333333333333,
  "repeatabilityN": 120,
  "betweenAppraisersPerTrial": 0.575,
  "allVsStandard": 0.425,
  "accuracy": 0.6,
  "missRate": 0.14814814814814814,
  "falseCallRate": 0.0,
  "warningRate": 0.425,
  "referenceWarningRate": 0.225,
  "fleissKappa": 0.43127962085308064,
  "judgments": 120
 },
 "after": {
  "repeatability": 0.775,
  "repeatabilityN": 120,
  "betweenAppraisersPerTrial": 0.6,
  "allVsStandard": 0.475,
  "accuracy": 0.6083333333333333,
  "missRate": 0.37037037037037035,
  "falseCallRate": 0.030303030303030304,
  "warningRate": 0.23333333333333334,
  "referenceWarningRate": 0.225,
  "fleissKappa": 0.39039408866995073,
  "judgments": 120
 },
 "recognition": {
  "CHP": {
   "refInstances": 27,
   "tp": 4,
   "fn": 23,
   "recall": 0.14814814814814814,
   "measBiasUm": -64.25
  },
  "CRK": {
   "refInstances": 6,
   "tp": 0,
   "fn": 6,
   "recall": 0.0,
   "measBiasUm": null
  },
  "SCR": {
   "refInstances": 24,
   "tp": 13,
   "fn": 11,
   "recall": 0.5416666666666666,
   "measBiasUm": 110.38461538461539
  },
  "CON": {
   "refInstances": 39,
   "tp": 23,
   "fn": 16,
   "recall": 0.5897435897435898,
   "measBiasUm": -23.695652173913043
  }
 }
};

export const HUMAN_SUMMARY: RawHumanSummary | null = {
 "appraiser": "作者本人",
 "date": "2026-10-06",
 "note": "兩輪同日進行、間隔不到一小時，可能有記憶效應；作者同時是檢驗規範 v1 的撰寫者。計時為作者口述，含找缺陷、量測與填表。第 1 輪 S18 未填。",
 "roundMinutes": [
  25,
  21
 ],
 "secondsPerDie": 34.9,
 "rounds": [
  {
   "round": 1,
   "own": {
    "n": 39,
    "accuracy": 0.6923076923076923,
    "missRate": 0.25,
    "falseCallRate": 0.045454545454545456,
    "warningRate": 0.2564102564102564
   },
   "rules": {
    "n": 39,
    "accuracy": 0.8461538461538461,
    "missRate": 0.25,
    "falseCallRate": 0.0,
    "warningRate": 0.1794871794871795
   },
   "fixedByRules": [
    "S08",
    "S14",
    "S20",
    "S25",
    "S31",
    "S32"
   ],
   "brokenByRules": []
  },
  {
   "round": 2,
   "own": {
    "n": 40,
    "accuracy": 0.725,
    "missRate": 0.2222222222222222,
    "falseCallRate": 0.0,
    "warningRate": 0.25
   },
   "rules": {
    "n": 40,
    "accuracy": 0.775,
    "missRate": 0.2222222222222222,
    "falseCallRate": 0.0,
    "warningRate": 0.25
   },
   "fixedByRules": [
    "S08",
    "S14",
    "S33",
    "S40"
   ],
   "brokenByRules": [
    "S01",
    "S38"
   ]
  }
 ],
 "combined": {
  "own": {
   "n": 79,
   "accuracy": 0.7088607594936709,
   "missRate": 0.23529411764705882,
   "falseCallRate": 0.022727272727272728,
   "warningRate": 0.25316455696202533
  },
  "rules": {
   "n": 79,
   "accuracy": 0.810126582278481,
   "missRate": 0.23529411764705882,
   "falseCallRate": 0.0,
   "warningRate": 0.21518987341772153
  },
  "fixedByRules": 10,
  "brokenByRules": 2
 },
 "repeatability": {
  "n": 39,
  "own": 0.8717948717948718,
  "rules": 0.8205128205128205
 }
};

export const HUMAN_REPLIES: RawHumanReply[] = [
 {
  "sample": "S19",
  "round": 1,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 20.0
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S08",
  "round": 1,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 20.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S24",
  "round": 1,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 15.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S17",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S23",
  "round": 1,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 105.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S22",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S07",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S11",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S25",
  "round": 1,
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 452.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S27",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S34",
  "round": 1,
  "defects": [
   {
    "code": "CRK",
    "zone": "core"
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S16",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S38",
  "round": 1,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 40.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S09",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S14",
  "round": 1,
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 45.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S01",
  "round": 1,
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 150.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S28",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S37",
  "round": 1,
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 250.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S35",
  "round": 1,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S02",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S32",
  "round": 1,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S03",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S05",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S10",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S15",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S04",
  "round": 1,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 20.0
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S06",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S26",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S20",
  "round": 1,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 75.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S21",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S31",
  "round": 1,
  "defects": [
   {
    "code": "CON",
    "zone": "peripheral",
    "diameterUm": 25.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S39",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S12",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S13",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S33",
  "round": 1,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 20.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S40",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S30",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S36",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S29",
  "round": 1,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S37",
  "round": 2,
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 110.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S07",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S32",
  "round": 2,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 20.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S13",
  "round": 2,
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 400.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S35",
  "round": 2,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 25.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S39",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S05",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S27",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S28",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S36",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S26",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S17",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S25",
  "round": 2,
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 452.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S03",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S04",
  "round": 2,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 25.0
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S34",
  "round": 2,
  "defects": [
   {
    "code": "CRK",
    "zone": "core"
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S10",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S31",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S21",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S01",
  "round": 2,
  "defects": [
   {
    "code": "SCR",
    "zone": "peripheral",
    "lengthUm": 150.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S19",
  "round": 2,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 30.0
   },
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 15.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S30",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S14",
  "round": 2,
  "defects": [
   {
    "code": "SCR",
    "zone": "core",
    "lengthUm": 55.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S24",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S22",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S18",
  "round": 2,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 140.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S33",
  "round": 2,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 15.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S20",
  "round": 2,
  "defects": [
   {
    "code": "CON",
    "zone": "core",
    "diameterUm": 50.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S11",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S38",
  "round": 2,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 25.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S40",
  "round": 2,
  "defects": [
   {
    "code": "CON",
    "zone": "peripheral",
    "diameterUm": 25.0
   }
  ],
  "ownVerdict": "warning",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S15",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S06",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S23",
  "round": 2,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 90.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "fail"
 },
 {
  "sample": "S08",
  "round": 2,
  "defects": [
   {
    "code": "CHP",
    "zone": "peripheral",
    "depthUm": 10.0
   }
  ],
  "ownVerdict": "fail",
  "pyRuleVerdict": "warning"
 },
 {
  "sample": "S12",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S29",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S02",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S16",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 },
 {
  "sample": "S09",
  "round": 2,
  "defects": [],
  "ownVerdict": "pass",
  "pyRuleVerdict": "pass"
 }
];

export const V2_SUMMARY: RawV2Summary | null = {
 "trial1": {
  "judgments": 120,
  "accuracy": 0.7583333333333333,
  "missRate": 0.0,
  "falseCallRate": 0.07575757575757576,
  "warningRate": 0.25833333333333336,
  "betweenAppraisersPerTrial": 0.825,
  "fleissKappa": 0.8219961856325494
 },
 "repeatability": 0.9249999999999999,
 "repeatabilityN": 120,
 "pooled": {
  "judgments": 240,
  "accuracy": 0.7583333333333333,
  "missRate": 0.0,
  "falseCallRate": 0.08333333333333333,
  "warningRate": 0.2625
 },
 "recognition": {
  "CHP": {
   "refInstances": 27,
   "tp": 19,
   "recall": 0.7037037037037037,
   "recallRelevant": 0.9444444444444444,
   "measBiasUm": 32.810526315789474,
   "measRelBias": 1.4700751879699248
  },
  "CRK": {
   "refInstances": 6,
   "tp": 6,
   "recall": 1.0,
   "recallRelevant": 1.0,
   "measBiasUm": 83.31666666666668,
   "measRelBias": 0.3865044633480362
  },
  "SCR": {
   "refInstances": 24,
   "tp": 24,
   "recall": 1.0,
   "recallRelevant": 1.0,
   "measBiasUm": 90.48333333333333,
   "measRelBias": 0.3660878386895759
  },
  "CON": {
   "refInstances": 39,
   "tp": 36,
   "recall": 0.9230769230769231,
   "recallRelevant": 0.9583333333333334,
   "measBiasUm": 7.955555555555555,
   "measRelBias": 0.451359126984127
  }
 },
 "falseCallsTrial1": [
  "S24/乙",
  "S24/甲",
  "S31/丙",
  "S31/乙",
  "S31/甲"
 ],
 "spendUsd": 9.55,
 "secondsPerDie": 8.2,
 "apiCalls": 240
};
